baseURL = "https://www.henriksommerfeld.se/"
languageCode = "en-gb"
title = "Henrik Sommerfeld's blog"
canonifyURLs = false
relativeURLs = false
buildDrafts = true
pagination.pagerSize = 5
pygmentsuseclasses = true
pygmentsstyle = "monokai"
preserveTaxonomyNames = true
disqusShortname = "henrik-sommerfeld"

[params]
    minifyBundles = false
    plausibleDomain = ""

[permalinks]
    article = "/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
