name: Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 #v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: 22

      - name: Install Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f #v3.0.0
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Install
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        id: e2e_tests
        run: npx playwright test

      - name: Send Pushover Notification
        uses: umahmood/pushover-actions@0582cb24dccd1fe77aeb35e6fb8027ddbca8af35
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'Blog PR'
          message: 'Test result: ${{ steps.e2e_tests.outcome }}'
          device: 'Gnutten'
          sound: ${{ job.status == 'success' && 'cosmic' || 'falling' }}
