name: Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: shidil/cloudflare-workers-preview@v1
        with:
          cf_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cf_account: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          domain: henrik-8ae.workers.dev
          project_path: blog-hugo
          teardown: 'true'
      - name: Get URL
        run: echo "https://${{ steps.preview_step.outputs.preview_url }}"
      - name: E2E tests
        run: |
          BASE_URL=${{ steps.cloudflare_preview_url.outputs.preview_url }} npx playwright test

      - name: Integration tests Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: job,repo,ref,author,took
          custom_payload: |
            {
              username: 'Integration tests',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Integration tests completed for repo ${process.env.AS_REPO}`,
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}
